### ISSUE TITLE
Hydrostatics for non-neutrally buoyant bodies

### ISSUE THREAD

**Issue by mancellin** [mancellin/capytaine#154]
It has been brought to my attention by @salhus that the current hydrostatics implementation assume the body to be in its buoyancy equilibrium position, with a mass equal to the displaced water mass.
Other cases might be of interest to model e.g. moored bodies.

For a single rigid body, formulas for the hydrostatic stiffness for non-neutrally buoyant bodies can be found in e.g. WAMIT manual.
For generalized dofs, we are investigating how to take that into account in our formula.

**Comment by mancellin** [comment]
### How should we let user specify the mass of the body?
For consistency, it might be good to have the same kind of interface as for the center of gravity
```
body.center_of_mass = np.array([0.0, 0.0, -1.0])
body.mass = 1500.0
```

However, `body.mass` is currently the canonical name for the inertia matrix (#56).
Maybe since we are making some big changes with the post-processing and the hydrostatics in the next release, it is a good time to come back on the choice of #56: name the inertia matrix `body.inertia_matrix` or `body.mass_matrix` to free the keyword `mass`.

**Comment by mancellin** [comment]
### Roadmap

- [ ] Add a `mass` property to the `FloatingBody` class
- [ ] Update the inertia matrix computation accordingly
- [ ] Update the hydrostatic stiffness for single rigid non-neutrally buoyant bodies
- Someday, update the hydrostatic stiffness for flexible bodies and multiple bodies.

**Comment by salhus** [comment]
Hi @mancellin 
I was thinking of just having the user input the body density instead of the mass. The advantage being that the body inertia matrix can then be populated with volume moments and the appropriate density of the body is multiplied. This would help avoid confusion with new inertia matrices and a potential source of error.

**Comment by mancellin** [comment]
Since there is a method to compute the volume of the mesh, I guess the code can convert from the body density into the body mass or vice-versa.
I would have expected setting the body mass to be more convenient for the user. What do you think?

**Comment by salhus** [comment]
Yes that makes sense. 
1. However, having the flexibility to change mass without having to deal with moments of inertias and second area moments can be handy. 
2. Also would allow changing the wetted surface lot easily, since the relative density can be tuned to help with design iterations.

Depends on the typical workflow. I think having mass might be easier for single run applications, but density might help when multiple runs are needed.

**Comment by mancellin** [comment]
> However, having the flexibility to change mass without having to deal with moments of inertias and second area moments can be handy.

I'm not sure to understand. Are you suggesting to add a `compute_volumic_inertia_matrix` such that user can more easily factor out the density?

**Comment by salhus** [comment]
Sorry i didnt word it more clearly. Yes that is exactly what i was suggesting.

**Comment by mancellin** [comment]
PR #166 implements the hydrostatics for *single rigid* non-neutrally buoyant bodies.
I guess this issue will remain open until the case of generalized dofs has been clarified.

**Comment by salhus** [comment]
@mancellin 
Cheers Matthieu. Looks good for now.
